### ISSUE TITLE
BUG: update behind corporate proxy is not working

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#56]
If I try to update the dragon tool with the -upgrade option behind corporate's firewall I get a HTTP connection time out error.
Error stack trace:

DRAGON Stack manager v2.0.6

> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> DRAGON upgrade ............................................................ ko
Upgrade failed because of network communication error!
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:555)
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at com.oracle.dragon.util.DSSession.checkForUpgrade(DSSession.java:871)
	at com.oracle.dragon.util.DSSession.work(DSSession.java:824)
	at com.oracle.dragon.DragonStack.main(DragonStack.java:42)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:68)
	at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1248)
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:877)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.net.ConnectException: HTTP connect timed out
	at jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:69)
	... 4 more
duration: 10s

I have the following environment variables setup in my terminal session:

ftp_proxy=<my proxy>
http_proxy=<my proxy>
https_proxy=<my proxy>
no_proxy=<my no_proxy list>

where <my proxy> is the address of my http proxy

**Comment by paolobellardone** [comment]
Not a bug. It was a network issue (firewall)
