### ISSUE TITLE
Load JSON fails if the file has only one row

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#72]
Running ./dragon-osx-x86_64-2.0.8 -loadjson to load one row of json data into a collection fails with the following error:
> JSON data loading ......................................................... ko
Collection testcoll files could not be loaded!
java.lang.RuntimeException: REST SQL Service could not run BEGIN
    DBMS_CLOUD.COPY_COLLECTION(
        collection_name => 'testcoll',
        credential_name => 'DRAGON_CREDENTIAL_NAME',
        file_uri_list => 'https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/emeaseitalysandbox/b/dragon/o/DRAGON/testcoll/*',
        format => JSON_OBJECT('recorddelimiter' value '''\n''', 'ignoreblanklines' value 'true') );
END;
/
	at com.oracle.dragon.util.ADBRESTService.execute(ADBRESTService.java:118)
	at com.oracle.dragon.util.DSSession.loadDataIntoCollections(DSSession.java:1952)
	at com.oracle.dragon.util.DSSession.loadDataIntoCollections(DSSession.java:1658)
	at com.oracle.dragon.util.DSSession.work(DSSession.java:946)
	at com.oracle.dragon.DragonStack.main(DragonStack.java:43)
Caused by: com.oracle.dragon.util.exception.ORDSSQLServiceException: Error (Line 1): ORA-20000: ORA-00913: too many values
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 1015
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 2706
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 2727
ORA-06512: at line 2
	at com.oracle.dragon.util.ADBRESTService.execute(ADBRESTService.java:110)
	... 4 more
duration: 2s

The source file is:
{"name":"document 1","content":"this is document one"}

If I put two rows in the file it works as expected.

**Comment by loiclefevre** [comment]
Fixed
