### ISSUE TITLE
-create-jet-app fails on mac dragon-osx-x86_64-2.2.0 with IllegalArgumentException: argument "src" is null

### ISSUE THREAD

**Issue by mshannongit** [loiclefevre/dragon#88]
```
mshannon@mshannon-mac(/developer/backupproject)% ./dragon-osx-x86_64-2.2.0 -create-react-app test
DRAGON Stack manager v2.2.0

> Local configuration ....................................................... ok
> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Stack creation .............................................. ok [React: test]
> Stack environment validation ..................................... ok [node14]
> Stack environment validation .............................................. ok
Success! Created test at /Users/mshannon/developer/backupproject/test
Inside that directory, you can run several commands:

  npm install
    Installs all the dependencies.

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can't go back!


We suggest that you begin by typing:

  cd test
  npm install
  npm start

Happy hacking!
duration: 0.196s
```

```
mshannon@mshannon-mac(/developer/backupproject)% ./dragon-osx-x86_64-2.2.0 -create-jet-app test2 
DRAGON Stack manager v2.2.0

> Local configuration ....................................................... ok
> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Stack creation .................................................... generating
================================================================================
Unhandled exception:
java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4755)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3582)
	at com.oracle.dragon.stacks.CodeGenerator.work(CodeGenerator.java:224)
	at com.oracle.dragon.util.DSSession.work(DSSession.java:1076)
	at com.oracle.dragon.DragonStack.main(DragonStack.java:44)

Reporting issues:
Please report any issue (bug, enhancement request, documentation needs...) at http://bit.ly/DragonStack in the "Issues" tab.
duration: 0.010s
```

**Comment by mshannongit** [comment]
stacks/create-jet-app/metadata.json appears not able to be read from within the graalvm native binary.

**Comment by loiclefevre** [comment]
@paolobellardone, have you tried this?

**Comment by paolobellardone** [comment]
> @paolobellardone, have you tried this?

Hi @loiclefevre Loic, I tested it with the current version and I get the same exception, I debugged the code and it seems that when dragon is invoked with "-create-jet-app" argument, the value of this code at row 224 of CodeGenerator.java:
`Thread.currentThread().getContextClassLoader().getResourceAsStream(rootResourcesDir + type.resourceDir + "/metadata.json"`
is not correctly evaluated and it returns a null

**Comment by loiclefevre** [comment]
Hi @paolobellardone, thank you for the confirmation. So I figured out that the GraalVM Native resources did not include the ones from the create-jet-app stack.

I've just pushed the file modified.

Could you please recompile it when you have time?

**Comment by paolobellardone** [comment]
I compiled and uploaded the new MacOS version, can you please test it?

**Comment by loiclefevre** [comment]
@mshannongit could you please run a test after re-downloading the latest MAC OS release? Thanks in advance

**Comment by loiclefevre** [comment]
Thanks @mshannongit for confirming it now works.
